services:
  redis:
    image: redis:7-alpine
    volumes:
      - redisdb:/data
    restart: always

  appedge:
    build: .
    env_file:
      - api.env
    ports:
      - "8080:8080"
    depends_on:
      - redis
    restart: always

volumes:
  redisdb:
    driver: local
