name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      POETRY_CACHE_DIR: ~/.cache/poetry
      POETRY_VIRTUALENVS_IN_PROJECT: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - uses: abatilo/actions-poetry@v2.1.4
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            ${{ env.POETRY_CACHE_DIR }}
            .venv
          key: linting-poetry-${{ hashFiles('api/poetry.lock') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ./api
        run: poetry install -n
      - name: Run tests
        working-directory: ./api
        run: poetry run pytest -svv
